version: "3.5"
services:
  database_master:
    image: mysql:8.0.30
    container_name: "database_master"
    restart: unless-stopped
    ports:
      - 3306:3306
    volumes:
      - mysqldata_master:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=kyoongdevSecret123!@#
      - MYSQL_USER=kyoong
      - MYSQL_DATABASE=body-times
      - MYSQL_PASSWORD=kyoongdevSecret123!@#
    networks:
      - mynetwork
networks:
  mynetwork:
volumes:
  mysqldata_master: