spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/body-times?serverTimezone=Asia/Seoul
    username: kyoong
    password: kyoongdevSecret123!@#
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true
  servlet:
    contextPath: /api/v1
  thymeleaf:
    cache: false


client_url: http://localhost:3000

social:
  kakao:
    clientId: 092fccd3b74f68a46c2c78542e80d985
    clientSecret: DLa3fqj2ccvSygkwEnJGD62FgXeVBH6w
    redirect-uri: http://localhost:8080/auth/social/kakao/callback
    scope:
      - account_email
      - profile_nickname
jwt:
  secret: 4uN1J3aA4ncaMHGIQZ0d1L0X5mLMTbpQ
  access_token_expires_in: 43200000 # 12시간
  refresh_token_expires_in: 604800000 # 7일

springdoc:
  swagger-ui:
    path: /api-docs

    groups-order: DESC # path, query, body, response ??? ??

    tags-sorter: alpha # ??? ??? ??? ??

    operations-sorter: method  # delete - get - patch - post - put ??? ??, alpha? ???? ??? ??? ?? ??

